spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Qwer1234!
    url: jdbc:mysql://localhost/WeChatOrder?charsetEncoding=utf-8?useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    enabled: true
    mode: HTML5
    suffix: .html

server:
  servlet:
    context-path: /takeaway




